/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as CompanySlugIndexRouteImport } from './routes/$companySlug/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardAdminRouteImport } from './routes/dashboard/admin'
import { Route as DashboardDriverRouteImport } from './routes/dashboard/driver'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as GoConviniRouteImport } from './routes/go.convini'
import { Route as GuidesFicaTipCreditRouteImport } from './routes/guides.fica-tip-credit'
import { Route as GuidesTipPoolingRouteImport } from './routes/guides.tip-pooling'
import { Route as JoinCodeRouteImport } from './routes/join.$code'
import { Route as PrintReviewsRouteImport } from './routes/print.reviews'
import { Route as PrintTipPayrollRouteImport } from './routes/print.tip-payroll'
import { Route as PrintVipRouteImport } from './routes/print.vip'
import { Route as CompanySlugDDriverSlugRouteImport } from './routes/$companySlug/d/$driverSlug'
import { Route as ApiAuthGoogleRouteImport } from './routes/api/auth/google'
import { Route as PrintEmployeeIdRouteImport } from './routes/print.employee.$id'
import { Route as ApiAuthGoogleCallbackRouteImport } from './routes/api/auth/google/callback'
import { Route as ApiPublicReviewsCompanySlugRouteImport } from './routes/api/public/reviews.$companySlug'
import { Route as ApiPublicWebhooksGhlRouteImport } from './routes/api/public/webhooks/ghl'
import { Route as ApiPublicWebhooksGhlEventsRouteImport } from './routes/api/public/webhooks/ghl-events'
import { Route as ApiPublicWebhooksStripeRouteImport } from './routes/api/public/webhooks/stripe'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanySlugIndexRoute = CompanySlugIndexRouteImport.update({
  id: '/$companySlug/',
  path: '/$companySlug/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/dashboard/admin',
  path: '/dashboard/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDriverRoute = DashboardDriverRouteImport.update({
  id: '/dashboard/driver',
  path: '/dashboard/driver',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const GoConviniRoute = GoConviniRouteImport.update({
  id: '/go/convini',
  path: '/go/convini',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesFicaTipCreditRoute = GuidesFicaTipCreditRouteImport.update({
  id: '/guides/fica-tip-credit',
  path: '/guides/fica-tip-credit',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesTipPoolingRoute = GuidesTipPoolingRouteImport.update({
  id: '/guides/tip-pooling',
  path: '/guides/tip-pooling',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinCodeRoute = JoinCodeRouteImport.update({
  id: '/join/$code',
  path: '/join/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintReviewsRoute = PrintReviewsRouteImport.update({
  id: '/print/reviews',
  path: '/print/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintTipPayrollRoute = PrintTipPayrollRouteImport.update({
  id: '/print/tip-payroll',
  path: '/print/tip-payroll',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintVipRoute = PrintVipRouteImport.update({
  id: '/print/vip',
  path: '/print/vip',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanySlugDDriverSlugRoute = CompanySlugDDriverSlugRouteImport.update({
  id: '/$companySlug/d/$driverSlug',
  path: '/$companySlug/d/$driverSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGoogleRoute = ApiAuthGoogleRouteImport.update({
  id: '/api/auth/google',
  path: '/api/auth/google',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintEmployeeIdRoute = PrintEmployeeIdRouteImport.update({
  id: '/print/employee/$id',
  path: '/print/employee/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGoogleCallbackRoute = ApiAuthGoogleCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => ApiAuthGoogleRoute,
} as any)
const ApiPublicReviewsCompanySlugRoute =
  ApiPublicReviewsCompanySlugRouteImport.update({
    id: '/api/public/reviews/$companySlug',
    path: '/api/public/reviews/$companySlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksGhlRoute = ApiPublicWebhooksGhlRouteImport.update({
  id: '/api/public/webhooks/ghl',
  path: '/api/public/webhooks/ghl',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksGhlEventsRoute =
  ApiPublicWebhooksGhlEventsRouteImport.update({
    id: '/api/public/webhooks/ghl-events',
    path: '/api/public/webhooks/ghl-events',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksStripeRoute = ApiPublicWebhooksStripeRouteImport.update({
  id: '/api/public/webhooks/stripe',
  path: '/api/public/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/driver': typeof DashboardDriverRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/go/convini': typeof GoConviniRoute
  '/guides/fica-tip-credit': typeof GuidesFicaTipCreditRoute
  '/guides/tip-pooling': typeof GuidesTipPoolingRoute
  '/join/$code': typeof JoinCodeRoute
  '/print/reviews': typeof PrintReviewsRoute
  '/print/tip-payroll': typeof PrintTipPayrollRoute
  '/print/vip': typeof PrintVipRoute
  '/$companySlug/': typeof CompanySlugIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/$companySlug/d/$driverSlug': typeof CompanySlugDDriverSlugRoute
  '/api/auth/google': typeof ApiAuthGoogleRouteWithChildren
  '/print/employee/$id': typeof PrintEmployeeIdRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
  '/api/public/reviews/$companySlug': typeof ApiPublicReviewsCompanySlugRoute
  '/api/public/webhooks/ghl': typeof ApiPublicWebhooksGhlRoute
  '/api/public/webhooks/ghl-events': typeof ApiPublicWebhooksGhlEventsRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/driver': typeof DashboardDriverRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/go/convini': typeof GoConviniRoute
  '/guides/fica-tip-credit': typeof GuidesFicaTipCreditRoute
  '/guides/tip-pooling': typeof GuidesTipPoolingRoute
  '/join/$code': typeof JoinCodeRoute
  '/print/reviews': typeof PrintReviewsRoute
  '/print/tip-payroll': typeof PrintTipPayrollRoute
  '/print/vip': typeof PrintVipRoute
  '/$companySlug': typeof CompanySlugIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/$companySlug/d/$driverSlug': typeof CompanySlugDDriverSlugRoute
  '/api/auth/google': typeof ApiAuthGoogleRouteWithChildren
  '/print/employee/$id': typeof PrintEmployeeIdRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
  '/api/public/reviews/$companySlug': typeof ApiPublicReviewsCompanySlugRoute
  '/api/public/webhooks/ghl': typeof ApiPublicWebhooksGhlRoute
  '/api/public/webhooks/ghl-events': typeof ApiPublicWebhooksGhlEventsRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/driver': typeof DashboardDriverRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/go/convini': typeof GoConviniRoute
  '/guides/fica-tip-credit': typeof GuidesFicaTipCreditRoute
  '/guides/tip-pooling': typeof GuidesTipPoolingRoute
  '/join/$code': typeof JoinCodeRoute
  '/print/reviews': typeof PrintReviewsRoute
  '/print/tip-payroll': typeof PrintTipPayrollRoute
  '/print/vip': typeof PrintVipRoute
  '/$companySlug/': typeof CompanySlugIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/$companySlug/d/$driverSlug': typeof CompanySlugDDriverSlugRoute
  '/api/auth/google': typeof ApiAuthGoogleRouteWithChildren
  '/print/employee/$id': typeof PrintEmployeeIdRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
  '/api/public/reviews/$companySlug': typeof ApiPublicReviewsCompanySlugRoute
  '/api/public/webhooks/ghl': typeof ApiPublicWebhooksGhlRoute
  '/api/public/webhooks/ghl-events': typeof ApiPublicWebhooksGhlEventsRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/privacy'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/unsubscribe'
    | '/dashboard/admin'
    | '/dashboard/driver'
    | '/email/unsubscribe'
    | '/go/convini'
    | '/guides/fica-tip-credit'
    | '/guides/tip-pooling'
    | '/join/$code'
    | '/print/reviews'
    | '/print/tip-payroll'
    | '/print/vip'
    | '/$companySlug/'
    | '/dashboard/'
    | '/$companySlug/d/$driverSlug'
    | '/api/auth/google'
    | '/print/employee/$id'
    | '/api/auth/google/callback'
    | '/api/public/reviews/$companySlug'
    | '/api/public/webhooks/ghl'
    | '/api/public/webhooks/ghl-events'
    | '/api/public/webhooks/stripe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/privacy'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/unsubscribe'
    | '/dashboard/admin'
    | '/dashboard/driver'
    | '/email/unsubscribe'
    | '/go/convini'
    | '/guides/fica-tip-credit'
    | '/guides/tip-pooling'
    | '/join/$code'
    | '/print/reviews'
    | '/print/tip-payroll'
    | '/print/vip'
    | '/$companySlug'
    | '/dashboard'
    | '/$companySlug/d/$driverSlug'
    | '/api/auth/google'
    | '/print/employee/$id'
    | '/api/auth/google/callback'
    | '/api/public/reviews/$companySlug'
    | '/api/public/webhooks/ghl'
    | '/api/public/webhooks/ghl-events'
    | '/api/public/webhooks/stripe'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/privacy'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/unsubscribe'
    | '/dashboard/admin'
    | '/dashboard/driver'
    | '/email/unsubscribe'
    | '/go/convini'
    | '/guides/fica-tip-credit'
    | '/guides/tip-pooling'
    | '/join/$code'
    | '/print/reviews'
    | '/print/tip-payroll'
    | '/print/vip'
    | '/$companySlug/'
    | '/dashboard/'
    | '/$companySlug/d/$driverSlug'
    | '/api/auth/google'
    | '/print/employee/$id'
    | '/api/auth/google/callback'
    | '/api/public/reviews/$companySlug'
    | '/api/public/webhooks/ghl'
    | '/api/public/webhooks/ghl-events'
    | '/api/public/webhooks/stripe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  DashboardAdminRoute: typeof DashboardAdminRoute
  DashboardDriverRoute: typeof DashboardDriverRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  GoConviniRoute: typeof GoConviniRoute
  GuidesFicaTipCreditRoute: typeof GuidesFicaTipCreditRoute
  GuidesTipPoolingRoute: typeof GuidesTipPoolingRoute
  JoinCodeRoute: typeof JoinCodeRoute
  PrintReviewsRoute: typeof PrintReviewsRoute
  PrintTipPayrollRoute: typeof PrintTipPayrollRoute
  PrintVipRoute: typeof PrintVipRoute
  CompanySlugIndexRoute: typeof CompanySlugIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  CompanySlugDDriverSlugRoute: typeof CompanySlugDDriverSlugRoute
  ApiAuthGoogleRoute: typeof ApiAuthGoogleRouteWithChildren
  PrintEmployeeIdRoute: typeof PrintEmployeeIdRoute
  ApiPublicReviewsCompanySlugRoute: typeof ApiPublicReviewsCompanySlugRoute
  ApiPublicWebhooksGhlRoute: typeof ApiPublicWebhooksGhlRoute
  ApiPublicWebhooksGhlEventsRoute: typeof ApiPublicWebhooksGhlEventsRoute
  ApiPublicWebhooksStripeRoute: typeof ApiPublicWebhooksStripeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$companySlug/': {
      id: '/$companySlug/'
      path: '/$companySlug'
      fullPath: '/$companySlug/'
      preLoaderRoute: typeof CompanySlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/dashboard/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/driver': {
      id: '/dashboard/driver'
      path: '/dashboard/driver'
      fullPath: '/dashboard/driver'
      preLoaderRoute: typeof DashboardDriverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/go/convini': {
      id: '/go/convini'
      path: '/go/convini'
      fullPath: '/go/convini'
      preLoaderRoute: typeof GoConviniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/fica-tip-credit': {
      id: '/guides/fica-tip-credit'
      path: '/guides/fica-tip-credit'
      fullPath: '/guides/fica-tip-credit'
      preLoaderRoute: typeof GuidesFicaTipCreditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/tip-pooling': {
      id: '/guides/tip-pooling'
      path: '/guides/tip-pooling'
      fullPath: '/guides/tip-pooling'
      preLoaderRoute: typeof GuidesTipPoolingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$code': {
      id: '/join/$code'
      path: '/join/$code'
      fullPath: '/join/$code'
      preLoaderRoute: typeof JoinCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/reviews': {
      id: '/print/reviews'
      path: '/print/reviews'
      fullPath: '/print/reviews'
      preLoaderRoute: typeof PrintReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/tip-payroll': {
      id: '/print/tip-payroll'
      path: '/print/tip-payroll'
      fullPath: '/print/tip-payroll'
      preLoaderRoute: typeof PrintTipPayrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/vip': {
      id: '/print/vip'
      path: '/print/vip'
      fullPath: '/print/vip'
      preLoaderRoute: typeof PrintVipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$companySlug/d/$driverSlug': {
      id: '/$companySlug/d/$driverSlug'
      path: '/$companySlug/d/$driverSlug'
      fullPath: '/$companySlug/d/$driverSlug'
      preLoaderRoute: typeof CompanySlugDDriverSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/google': {
      id: '/api/auth/google'
      path: '/api/auth/google'
      fullPath: '/api/auth/google'
      preLoaderRoute: typeof ApiAuthGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/employee/$id': {
      id: '/print/employee/$id'
      path: '/print/employee/$id'
      fullPath: '/print/employee/$id'
      preLoaderRoute: typeof PrintEmployeeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/google/callback': {
      id: '/api/auth/google/callback'
      path: '/callback'
      fullPath: '/api/auth/google/callback'
      preLoaderRoute: typeof ApiAuthGoogleCallbackRouteImport
      parentRoute: typeof ApiAuthGoogleRoute
    }
    '/api/public/reviews/$companySlug': {
      id: '/api/public/reviews/$companySlug'
      path: '/api/public/reviews/$companySlug'
      fullPath: '/api/public/reviews/$companySlug'
      preLoaderRoute: typeof ApiPublicReviewsCompanySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/ghl': {
      id: '/api/public/webhooks/ghl'
      path: '/api/public/webhooks/ghl'
      fullPath: '/api/public/webhooks/ghl'
      preLoaderRoute: typeof ApiPublicWebhooksGhlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/ghl-events': {
      id: '/api/public/webhooks/ghl-events'
      path: '/api/public/webhooks/ghl-events'
      fullPath: '/api/public/webhooks/ghl-events'
      preLoaderRoute: typeof ApiPublicWebhooksGhlEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/stripe': {
      id: '/api/public/webhooks/stripe'
      path: '/api/public/webhooks/stripe'
      fullPath: '/api/public/webhooks/stripe'
      preLoaderRoute: typeof ApiPublicWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiAuthGoogleRouteChildren {
  ApiAuthGoogleCallbackRoute: typeof ApiAuthGoogleCallbackRoute
}

const ApiAuthGoogleRouteChildren: ApiAuthGoogleRouteChildren = {
  ApiAuthGoogleCallbackRoute: ApiAuthGoogleCallbackRoute,
}

const ApiAuthGoogleRouteWithChildren = ApiAuthGoogleRoute._addFileChildren(
  ApiAuthGoogleRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  DashboardAdminRoute: DashboardAdminRoute,
  DashboardDriverRoute: DashboardDriverRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  GoConviniRoute: GoConviniRoute,
  GuidesFicaTipCreditRoute: GuidesFicaTipCreditRoute,
  GuidesTipPoolingRoute: GuidesTipPoolingRoute,
  JoinCodeRoute: JoinCodeRoute,
  PrintReviewsRoute: PrintReviewsRoute,
  PrintTipPayrollRoute: PrintTipPayrollRoute,
  PrintVipRoute: PrintVipRoute,
  CompanySlugIndexRoute: CompanySlugIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  CompanySlugDDriverSlugRoute: CompanySlugDDriverSlugRoute,
  ApiAuthGoogleRoute: ApiAuthGoogleRouteWithChildren,
  PrintEmployeeIdRoute: PrintEmployeeIdRoute,
  ApiPublicReviewsCompanySlugRoute: ApiPublicReviewsCompanySlugRoute,
  ApiPublicWebhooksGhlRoute: ApiPublicWebhooksGhlRoute,
  ApiPublicWebhooksGhlEventsRoute: ApiPublicWebhooksGhlEventsRoute,
  ApiPublicWebhooksStripeRoute: ApiPublicWebhooksStripeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
