/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as JoinCodeRouteImport } from './routes/join.$code'
import { Route as GuidesTipPoolingRouteImport } from './routes/guides.tip-pooling'
import { Route as GuidesFicaTipCreditRouteImport } from './routes/guides.fica-tip-credit'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as DashboardDriverRouteImport } from './routes/dashboard/driver'
import { Route as DashboardAdminRouteImport } from './routes/dashboard/admin'
import { Route as PrintEmployeeIdRouteImport } from './routes/print.employee.$id'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as CompanySlugDDriverSlugRouteImport } from './routes/$companySlug/d/$driverSlug'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ApiPublicWebhooksStripeRouteImport } from './routes/api/public/webhooks/stripe'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinCodeRoute = JoinCodeRouteImport.update({
  id: '/join/$code',
  path: '/join/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesTipPoolingRoute = GuidesTipPoolingRouteImport.update({
  id: '/guides/tip-pooling',
  path: '/guides/tip-pooling',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesFicaTipCreditRoute = GuidesFicaTipCreditRouteImport.update({
  id: '/guides/fica-tip-credit',
  path: '/guides/fica-tip-credit',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDriverRoute = DashboardDriverRouteImport.update({
  id: '/dashboard/driver',
  path: '/dashboard/driver',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/dashboard/admin',
  path: '/dashboard/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintEmployeeIdRoute = PrintEmployeeIdRouteImport.update({
  id: '/print/employee/$id',
  path: '/print/employee/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanySlugDDriverSlugRoute = CompanySlugDDriverSlugRouteImport.update({
  id: '/$companySlug/d/$driverSlug',
  path: '/$companySlug/d/$driverSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksStripeRoute = ApiPublicWebhooksStripeRouteImport.update({
  id: '/api/public/webhooks/stripe',
  path: '/api/public/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/driver': typeof DashboardDriverRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/guides/fica-tip-credit': typeof GuidesFicaTipCreditRoute
  '/guides/tip-pooling': typeof GuidesTipPoolingRoute
  '/join/$code': typeof JoinCodeRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/$companySlug/d/$driverSlug': typeof CompanySlugDDriverSlugRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/print/employee/$id': typeof PrintEmployeeIdRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/driver': typeof DashboardDriverRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/guides/fica-tip-credit': typeof GuidesFicaTipCreditRoute
  '/guides/tip-pooling': typeof GuidesTipPoolingRoute
  '/join/$code': typeof JoinCodeRoute
  '/dashboard': typeof DashboardIndexRoute
  '/$companySlug/d/$driverSlug': typeof CompanySlugDDriverSlugRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/print/employee/$id': typeof PrintEmployeeIdRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/driver': typeof DashboardDriverRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/guides/fica-tip-credit': typeof GuidesFicaTipCreditRoute
  '/guides/tip-pooling': typeof GuidesTipPoolingRoute
  '/join/$code': typeof JoinCodeRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/$companySlug/d/$driverSlug': typeof CompanySlugDDriverSlugRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/print/employee/$id': typeof PrintEmployeeIdRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/unsubscribe'
    | '/dashboard/admin'
    | '/dashboard/driver'
    | '/email/unsubscribe'
    | '/guides/fica-tip-credit'
    | '/guides/tip-pooling'
    | '/join/$code'
    | '/dashboard/'
    | '/$companySlug/d/$driverSlug'
    | '/lovable/email/suppression'
    | '/print/employee/$id'
    | '/api/public/webhooks/stripe'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/unsubscribe'
    | '/dashboard/admin'
    | '/dashboard/driver'
    | '/email/unsubscribe'
    | '/guides/fica-tip-credit'
    | '/guides/tip-pooling'
    | '/join/$code'
    | '/dashboard'
    | '/$companySlug/d/$driverSlug'
    | '/lovable/email/suppression'
    | '/print/employee/$id'
    | '/api/public/webhooks/stripe'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/unsubscribe'
    | '/dashboard/admin'
    | '/dashboard/driver'
    | '/email/unsubscribe'
    | '/guides/fica-tip-credit'
    | '/guides/tip-pooling'
    | '/join/$code'
    | '/dashboard/'
    | '/$companySlug/d/$driverSlug'
    | '/lovable/email/suppression'
    | '/print/employee/$id'
    | '/api/public/webhooks/stripe'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  DashboardAdminRoute: typeof DashboardAdminRoute
  DashboardDriverRoute: typeof DashboardDriverRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  GuidesFicaTipCreditRoute: typeof GuidesFicaTipCreditRoute
  GuidesTipPoolingRoute: typeof GuidesTipPoolingRoute
  JoinCodeRoute: typeof JoinCodeRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  CompanySlugDDriverSlugRoute: typeof CompanySlugDDriverSlugRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  PrintEmployeeIdRoute: typeof PrintEmployeeIdRoute
  ApiPublicWebhooksStripeRoute: typeof ApiPublicWebhooksStripeRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$code': {
      id: '/join/$code'
      path: '/join/$code'
      fullPath: '/join/$code'
      preLoaderRoute: typeof JoinCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/tip-pooling': {
      id: '/guides/tip-pooling'
      path: '/guides/tip-pooling'
      fullPath: '/guides/tip-pooling'
      preLoaderRoute: typeof GuidesTipPoolingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/fica-tip-credit': {
      id: '/guides/fica-tip-credit'
      path: '/guides/fica-tip-credit'
      fullPath: '/guides/fica-tip-credit'
      preLoaderRoute: typeof GuidesFicaTipCreditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/driver': {
      id: '/dashboard/driver'
      path: '/dashboard/driver'
      fullPath: '/dashboard/driver'
      preLoaderRoute: typeof DashboardDriverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/dashboard/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/employee/$id': {
      id: '/print/employee/$id'
      path: '/print/employee/$id'
      fullPath: '/print/employee/$id'
      preLoaderRoute: typeof PrintEmployeeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$companySlug/d/$driverSlug': {
      id: '/$companySlug/d/$driverSlug'
      path: '/$companySlug/d/$driverSlug'
      fullPath: '/$companySlug/d/$driverSlug'
      preLoaderRoute: typeof CompanySlugDDriverSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/stripe': {
      id: '/api/public/webhooks/stripe'
      path: '/api/public/webhooks/stripe'
      fullPath: '/api/public/webhooks/stripe'
      preLoaderRoute: typeof ApiPublicWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  DashboardAdminRoute: DashboardAdminRoute,
  DashboardDriverRoute: DashboardDriverRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  GuidesFicaTipCreditRoute: GuidesFicaTipCreditRoute,
  GuidesTipPoolingRoute: GuidesTipPoolingRoute,
  JoinCodeRoute: JoinCodeRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  CompanySlugDDriverSlugRoute: CompanySlugDDriverSlugRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  PrintEmployeeIdRoute: PrintEmployeeIdRoute,
  ApiPublicWebhooksStripeRoute: ApiPublicWebhooksStripeRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
